# This file contains the configuration for Supabase settings.

[project]
name = "tenant-management-app"
region = "us-east-1"

[database]
url = "https://hgcahrdknmfbwczdaerv.supabase.co"
anon_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhnY2FocmRrbm1mYndjemRhZXJ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3NDU4OTcsImV4cCI6MjA3MDMyMTg5N30.0L6gqS1rtc8uPg8CICLFLm-qVzBSg8PeQTMAV46NXXs"
service_role_key = "your-service-role-key"

[auth]
jwt_secret = "your-jwt-secret"

[storage]
bucket_name = "your-bucket-name"